#!/usr/bin/env python
"""
================================================================================
DJANGO MANAGEMENT UTILITY
================================================================================

Django's command-line utility for administrative tasks.

This script is the main entry point for running Django management commands.
It handles Django initialization, settings loading, and command execution.

COMMON USAGE:

Development Server:
  python manage.py runserver              - Start development server (port 8000)
  python manage.py runserver 0.0.0.0:8000 - Accessible from network

Database:
  python manage.py migrate                - Apply pending migrations
  python manage.py makemigrations         - Create migration files from models
  python manage.py showmigrations         - List all migrations
  python manage.py migrate api_features zero  - Rollback all migrations

Admin:
  python manage.py createsuperuser        - Create admin account
  python manage.py changepassword user    - Change user password

Debugging:
  python manage.py shell                  - Interactive Python shell
  python manage.py dbshell                - Database-specific shell

Testing:
  python manage.py test                   - Run all tests
  python manage.py test api_features      - Run app-specific tests

Files & Static Assets:
  python manage.py collectstatic          - Collect static files (production)
  python manage.py findstatic <file>      - Find static file location

Utilities:
  python manage.py check                  - Check for configuration issues
  python manage.py flush                  - Empty database (deletes data!)
  python manage.py graph_models           - Generate model diagram (requires graphviz)

ENVIRONMENT VARIABLES:
  DJANGO_SETTINGS_MODULE  - Path to settings file (default: MalumAI.settings)

CUSTOM COMMANDS:
You can create custom management commands in:
  app_name/management/commands/command_name.py

Then run with:
  python manage.py command_name

HELP SYSTEM:
  python manage.py help               - List all commands
  python manage.py help <command>     - Show help for specific command

TROUBLESHOOTING:

  "ModuleNotFoundError: No module named 'django'"
    → Install Django: pip install django

  "Settings not found"
    → Check DJANGO_SETTINGS_MODULE environment variable
    → Ensure MalumAI/settings.py exists

  Database errors
    → Run: python manage.py migrate

INSTALLATION:
This file is auto-generated by Django when you create a new project:
  django-admin startproject MalumAI

DO NOT EDIT: This file should not be modified unless you know what you do.

================================================================================
"""
import os
import sys


def main():
    """
    Run administrative tasks.
    
    PROCESS:
      1. Set default Django settings module
      2. Import Django management
      3. Execute command from sys.argv
      4. Handle import errors gracefully
    
    This function is called when the script runs:
      python manage.py <command> [arguments]
    """
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'MalumAI.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


# == SCRIPT ENTRY POINT ==
if __name__ == '__main__':
    main()
