"""
================================================================================
MALUMIA - DJANGO CONFIGURATION SETTINGS
================================================================================

Django configuration for the MalumAI project.

Generated by 'django-admin startproject' using Django 6.0.2.

OVERVIEW:
This file contains all configuration settings for the Django application,
including database configuration, installed applications, middleware, 
authentication, static files, and API keys.

CRITICAL SETTINGS:

  DEBUG = True
    - DEVELOPMENT MODE ENABLED
    - Never set to True in production
    - Exposes detailed error pages and source code

  SECRET_KEY
    - Used for session signing and CSRF tokens
    - Change in production and keep secret
    - Never commit real keys to version control

  ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    - Hosts allowed to serve the application
    - Add production domains before deployment

  INSTALLED_APPS
    - api_features        (Custom app for AI features)
    - django.contrib.*    (Django built-in apps)

  MIDDLEWARE
    - Security, sessions, authentication, CSRF protection
    - Order matters; processed top to bottom

DATABASES:
  SQLite (db.sqlite3) - Default development database
  Migrate to PostgreSQL/MySQL for production

KEY COMPONENTS:
  - Static files: CSS, JS, images served by Django in development
  - Templates: HTML files for rendering views
  - Migrations: Schema version control

DOCUMENTATION:
  Full settings reference: https://docs.djangoproject.com/en/6.0/ref/settings/
  Deployment checklist: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

ENVIRONMENT VARIABLES:
  Consider using python-decouple or django-environ for:
  - SECRET_KEY
  - DATABASE credentials
  - API keys

LAST MODIFIED: February 2026

================================================================================
"""

"""
Django settings for MalumAI project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^7*^y_sdwd6rygp&#d77fle#8)vqs)fs9^a!8-98&r%ykur@6a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api_features',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MalumAI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MalumAI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
